In [ ]:
%pip install numpy
import numpy as np

In [3]:
a = [[11, 12, 13], [21, 22, 23], [31, 32, 33]]
arr = np.array(a)
arr

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [4]:
arr.ndim

2

In [5]:
arr.shape

(3, 3)

In [6]:
arr.size

9

In [ ]:
arr[1, 2]

# [11, 12, 13],
# [21, 22, (23)],
# [31, 32, 33]

np.int64(23)

In [ ]:
arr[1][2]

# [11, 12, 13],
# [21, 22, (23)],
# [31, 32, 33]

np.int64(23)

In [ ]:
arr[0][0]

# [(11), 12, 13],
# [21, 22, 23],
# [31, 32, 33]

np.int64(11)

In [21]:
# slicing
print(arr[0][0:2])
print(arr[0:2, 2])

# [(11, 12), 13],
# [21, 22, 23],
# [31, 32, 33]

[11 12]
[13 23]


In [24]:
X = np.array([[1, 0], [0, 1]])
Y = np.array([[2, 1], [1, 2]])

print(X)
print("\n")
print(Y)

[[1 0]
 [0 1]]


[[2 1]
 [1 2]]


In [ ]:
# X = np.array([[1, 0], [0, 1]])
# Y = np.array([[2, 1], [1, 2]])
Z = X + Y
print(Z)

[[3 1]
 [1 3]]


In [ ]:
# X = np.array([[1, 0], [0, 1]])
# Y = np.array([[2, 1], [1, 2]])
Z = 2 * Y
print(Z)

[[4 2]
 [2 4]]


In [28]:
# X = np.array([[1, 0], [0, 1]])
# Y = np.array([[2, 1], [1, 2]])
Z = X * Y
print(Z)

[[2 0]
 [0 2]]


In [29]:
# X = np.array([[1, 0], [0, 1]])
# Y = np.array([[2, 1], [1, 2]])
Z = np.dot(X, Y)
print(Z)

[[2 1]
 [1 2]]


In [31]:
sin = np.sin(Z)
sin

array([[0.90929743, 0.84147098],
       [0.84147098, 0.90929743]])

In [38]:
# transposed
C = np.array([[1, 2], [2, 3], [4, 5]])

C.T

array([[1, 2, 4],
       [2, 3, 5]])

In [44]:
X = np.array([[1, 0], [0, 1]])

Y = np.array([[2, 2], [2, 2]])

Z = np.dot(X, Y)
Z

array([[2, 2],
       [2, 2]])