In [ ]:
%pip install numpy matplotlib
# import numpy library
import numpy as np

In [4]:
# Create a numpy array
arr = np.array([0, 1, 2, 3, 4])
arr

array([0, 1, 2, 3, 4])

In [6]:
print(arr[0])
print(arr[1])
print(arr[2])
print(arr[3])
print(arr[4])

0
1
2
3
4


In [7]:
print(np.__version__)

2.3.3


In [8]:
type(arr)

numpy.ndarray

In [9]:
arr.dtype

dtype('int64')

In [10]:
arr[4] = 100
arr

array([  0,   1,   2,   3, 100])

In [11]:
arr2 = arr[1:3]
arr2

array([1, 2])

In [17]:
arr[3:5] = 300, 400
arr

array([  0,   1,   2, 300, 400])

In [18]:
select = [0, 2, 3, 4]
select

[0, 2, 3, 4]

In [ ]:
# select by indexes
selected = arr[select]
selected

array([  0,   2, 300, 400])

In [ ]:
# assign value to selected indexes
arr[select] = 1000
arr

array([1000,    1, 1000, 1000, 1000])

In [23]:
arr3 = np.array([0, 1, 2, 3, 4])
arr3

array([0, 1, 2, 3, 4])

In [26]:
# array size (length)
arr3.size

5

In [27]:
# number of array dimensions
arr3.ndim

1

In [29]:
# size in dimensions (5 elements in 1 dimension)
arr3.shape

(5,)

In [ ]:
# avarage value in array
mean = arr3.mean()
mean

np.float64(2.0)

In [31]:
max_arr3 = arr3.max()
max_arr3

np.int64(4)

In [32]:
min_arr3 = arr3.min()
min_arr3

np.int64(0)

In [ ]:
# vector u
u = np.array([1, 0])
# vector v
v = np.array([0, 1])

# adding vectors
z = np.add(u, v)

z

array([1, 1])

In [ ]:
# Plotting functions

import matplotlib.pyplot as plt


def plot_vector1(u, z, v):
    pass

<module 'matplotlib.pyplot' from '/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/matplotlib/pyplot.py'>